server:
  port: 8080
springdoc:
  api-docs:
    version: openapi_3_0
spring:
  name: Account
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: raju
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
