
spring:
  application:
    name: "configserver"
  profiles:
    active: git
    #active: native #(only use when reading configurations from classpath or file System)
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/mkmeena97/ASPL-config-server.git"
          #username: mkmeena97
          #password: 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
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "file:///C://Users//mahendra//Desktop//ASPL//config"
          #search-locations: "classpath:/config"
#  rabbitmq:
#    host: "rabbit"
#    port: 5672
#    username: "guest"
#    password: "guest"
encrypt:
  key: "37DR56hDhTfh#$%%%38"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true