services:
  accountsdb:
    image: postgres
    container_name: accountsdb
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: accountsdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d accountsdb" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-deploy-service

  loansdb:
    container_name: loansdb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: microservice-mysqldb-config

  cardsdb:
    container_name: cardsdb
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: microservice-mysqldb-config

  configserver:
    image: "mkmeena97/configserver:s7"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    extends:
      file: common-config.yml
      service: microservice-base-config

  accounts:
    image: "mkmeena97/accounts:s7"
    container_name: accounts-ms
    ports:
      - "8081:8081"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8071/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://accountsdb:5433/accountsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config


  loans:
    image: "mkmeena97/loans:s7"
    container_name: loans-ms
    ports:
      - "8082:8082"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3309/loansdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  cards:
    image: "mkmeena97/cards:s7"
    container_name: cards-ms
    ports:
      - "8083:8083"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3308/cardsdb"
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  aspl:
    driver: "bridge"