services:
  accounts:
    image: "mkmeena97/accounts:aspl-bank-microservice"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: '0.5'
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aspl


  loans:
    image: "mkmeena97/loans:aspl-bank-microservice"
    container_name: loans-ms
    ports:
      - "8081:8081"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: '0.5'
    networks:
      - aspl


  cards:
    image: "mkmeena97/cards:aspl-bank-microservice"
    container_name: cards-ms
    ports:
      - "8082:8082"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
          cpus: '0.5'
    networks:
      - aspl


networks:
  aspl:
    driver: "bridge"